# Generated by Django 5.2.8 on 2025-11-24 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service name (e.g., Neurosciences, Cardiology)', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('banner_image_desktop', models.ImageField(help_text='Desktop banner image', upload_to='services/banners/')),
                ('banner_image_mobile', models.ImageField(blank=True, help_text='Mobile banner image (optional)', null=True, upload_to='services/banners/')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('overview_title', models.CharField(default='Overview', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ailment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='services/ailments/')),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ailments', to='base.service')),
            ],
            options={
                'verbose_name': 'Ailment',
                'verbose_name_plural': 'Ailments',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAccordion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('subspecialization', 'Sub-Specialization'), ('faq', 'FAQ'), ('other', 'Other')], default='other', max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accordions', to='base.service')),
            ],
            options={
                'verbose_name': 'Service Accordion',
                'verbose_name_plural': 'Service Accordions',
                'ordering': ['section_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Doctor's full name", max_length=200)),
                ('title', models.CharField(help_text='e.g., Chairman, Institute Of Neurosciences', max_length=300)),
                ('image', models.ImageField(help_text="Doctor's photo", upload_to='services/doctors/')),
                ('message', models.TextField(help_text='Message/description from the doctor')),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='base.service')),
            ],
            options={
                'verbose_name': 'Service Doctor',
                'verbose_name_plural': 'Service Doctors',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='base.service')),
            ],
            options={
                'verbose_name': 'Service Feature',
                'verbose_name_plural': 'Service Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Team section title', max_length=300)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle', max_length=500)),
                ('image', models.ImageField(upload_to='services/teams/')),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='base.service')),
            ],
            options={
                'verbose_name': 'Service Team',
                'verbose_name_plural': 'Service Teams',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, help_text='Optional - can be anonymous', max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('story', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/success_stories/')),
                ('video_url', models.URLField(blank=True, help_text='Optional YouTube/Vimeo URL')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_stories', to='base.service')),
            ],
            options={
                'verbose_name': 'Success Story',
                'verbose_name_plural': 'Success Stories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='services/technologies/')),
                ('short_description', models.TextField(help_text='Brief description (shown in card)')),
                ('full_description', models.TextField(blank=True, help_text='Full description (optional)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='base.service')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='services/treatments/')),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='base.service')),
            ],
            options={
                'verbose_name': 'Treatment',
                'verbose_name_plural': 'Treatments',
                'ordering': ['order'],
            },
        ),
    ]
