# Generated by Django 5.2.8 on 2025-11-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, help_text='Icon for navigation menu (26x26px recommended)', null=True, upload_to='services/icons/'),
        ),
    ]
