# Generated by Django 5.2.8 on 2025-11-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ailment',
            name='image',
            field=models.ImageField(blank=True, help_text='Ailment image (optional)', null=True, upload_to='services/ailments/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='banner_image_desktop',
            field=models.ImageField(blank=True, help_text='Desktop banner image (optional)', null=True, upload_to='services/banners/'),
        ),
        migrations.AlterField(
            model_name='servicedoctor',
            name='image',
            field=models.ImageField(blank=True, help_text="Doctor's photo (optional)", null=True, upload_to='services/doctors/'),
        ),
        migrations.AlterField(
            model_name='serviceteam',
            name='image',
            field=models.ImageField(blank=True, help_text='Team image (optional)', null=True, upload_to='services/teams/'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='image',
            field=models.ImageField(blank=True, help_text='Technology image (optional)', null=True, upload_to='services/technologies/'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='image',
            field=models.ImageField(blank=True, help_text='Treatment image (optional)', null=True, upload_to='services/treatments/'),
        ),
    ]
