# Generated by Django 5.2.8 on 2025-11-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_ailment_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='card_image',
            field=models.ImageField(blank=True, help_text='Image for service cards', null=True, upload_to='services/cards/'),
        ),
        migrations.AddField(
            model_name='service',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Logo image for service cards', null=True, upload_to='services/logos/'),
        ),
        migrations.AddField(
            model_name='service',
            name='model_of_care_image',
            field=models.ImageField(blank=True, help_text='Image for Model of Care section', null=True, upload_to='services/model_of_care/'),
        ),
        migrations.AddField(
            model_name='service',
            name='model_of_care_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order in Model of Care section'),
        ),
        migrations.AddField(
            model_name='service',
            name='services_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order in Services section'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short description for homepage cards'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_in_model_of_care',
            field=models.BooleanField(default=False, help_text='Show in Model of Care section on homepage'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_in_services',
            field=models.BooleanField(default=False, help_text='Show in Services section on homepage'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_in_specialities',
            field=models.BooleanField(default=False, help_text='Show in Specialities section on homepage'),
        ),
        migrations.AddField(
            model_name='service',
            name='specialities_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order in Specialities section'),
        ),
    ]
